#!/usr/bin/env bash
# To use an OpenStack cloud you need to authenticate against the Identity
# service named keystone, which returns a **Token** and **Service Catalog**.
# The catalog contains the endpoints for all services the user/tenant has
# access to - such as Compute, Image Service, Identity, Object Storage, Block
# Storage, and Networking (code-named nova, glance, keystone, swift,
# cinder, and neutron).
#
# *NOTE*: Using the 3 *Identity API* does not necessarily mean any other
# OpenStack API is version 3. For example, your cloud provider may implement
# Image API v1.1, Block Storage API v2, and Compute API v2.0. OS_AUTH_URL is
# only for the Identity API served through keystone.
export TF_VAR_OS_AUTH_URL=http://192.168.219.108/identity
# With the addition of Keystone we have standardized on the term **project**
# as the entity that owns the resources.
export TF_VAR_OS_PROJECT_ID=b075dcc8657f4e8a9d70052d00a3c5a3
export TF_VAR_OS_PROJECT_NAME="demo"
export TF_VAR_OS_USER_DOMAIN_NAME="Default"
if [ -z "$TF_VAR_OS_USER_DOMAIN_NAME" ]; then unset OS_USER_DOMAIN_NAME; fi
export TF_VAR_OS_PROJECT_DOMAIN_ID="default"
if [ -z "$TF_VAR_OS_PROJECT_DOMAIN_ID" ]; then unset OS_PROJECT_DOMAIN_ID; fi
# unset v2.0 items in case set
unset TF_VAR_OS_TENANT_ID
unset TF_VAR_OS_TENANT_NAME
# In addition to the owning entity (tenant), OpenStack stores the entity
# performing the action as the **user**.
export TF_VAR_OS_USERNAME="admin"
# With Keystone you pass the keystone password.
echo "Please enter your OpenStack Password for project $TF_VAR_OS_PROJECT_NAME as user $TF_VAR_OS_USERNAME: "
read -sr TF_VAR_OS_PASSWORD_INPUT
export TF_VAR_OS_PASSWORD=$OS_PASSWORD_INPUT
# If your configuration has multiple regions, we set that information here.
# OS_REGION_NAME is optional and only valid in certain environments.
export TF_VAR_OS_REGION_NAME="RegionOne"
# Don't leave a blank variable, unset it if it was empty
if [ -z "$TF_VAR_OS_REGION_NAME" ]; then unset OS_REGION_NAME; fi
export TF_VAR_OS_INTERFACE=public
export TF_VAR_OS_IDENTITY_API_VERSION=3
